DeepUtils
RegularExpressionKft/alien-utils pull request #15
Opened 2019-09-11 13:52 UTC by SaturnV

2019-09-11 14:13 UTC, tasika16 requested changes

2019-09-11 14:13 UTC, tasika16 commented on deep.coffee
> +    result[k] = b: v
Ez itt hátra vetett for-ba nem mehet?

2019-09-11 14:13 UTC, tasika16 commented on deep.coffee
> +    _diff a, b
Egy sorba mint lejeb és feljebb vagy nem fér ki?

2019-09-11 14:26 UTC, SaturnV commented on deep.coffee
> +    result[k] = b: v
done

2019-09-11 14:26 UTC, SaturnV commented on deep.coffee
> +    _diff a, b
done

2019-09-12 08:20 UTC, mullerzs commented on deep.coffee
> +    b: b
Furcsa ez így, hogy ha az összehasonlítandó objektumokban is van "a" és "b"...

2019-09-12 09:47 UTC, SaturnV commented on deep.coffee
> +    b: b
És tényleg. Ezt most huszárvágom. :)

2019-09-12 11:29 UTC, merged